version: '2'
services:
    php:
        image: php:fpm
        links:
          - "mysql"
        volumes:
          - ./zentaopms:/data/zentao/zentaopms
          - ./php:/usr/local/etc/php

    mysql:
        image: mysql
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: zentao@mysql

    nginx:
        image: nginx
        ports:
          - "8080:80"
        links:
          - "php"
        volumes:
          - ./zentaopms:/data/zentao/zentaopms
          - ./nginx/conf.d:/etc/nginx/conf.d